version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Choose either one of the orbs below
  # welcome: circleci/welcome-orb@0.4.1
  aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project
jobs:
  create_infrastructure: 
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        - run:
            name: Create Cloudformation Stack
            command: |
              aws cloudformation deploy \
                --template-file template.yml \
                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                --region us-east-1

  launch_ec2_webserver:
      steps:
        - checkout
        - run:
            name: create webserver
            command: |
              ansible-playbook \
              main-remote.yml \
              -i inventory \
              --private-key project_udacity    
# Sequential workflow
workflows:
  # Name the workflow
  cloudworkflows:
    jobs:
      - create_infrastructure
      - launch_ec2_webserver